### ISSUE TITLE
There was an error building this page

### ISSUE THREAD

**Issue by amutaher** [frappe/wiki#10]
After installing wiki to my site the default route was _home_ when I click on **see on website** its show my homepage
then I change route to wiki/home now when I click on **see on website** i get this error:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 1, in top-level template code
    {% extends "wiki/doctype/wiki_page/templates/wiki_doc.html" %}
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 2, in top-level template code
    {%- from "templates/includes/navbar/navbar_items.html" import render_item -%}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 77, in block "content"
    {% block page_container %}
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 83, in block "page_container"
    {%- block page_content -%}{%- endblock -%}
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 19, in block "page_content"
    {% include "wiki/doctype/wiki_page/templates/show.html" %}
  File "/home/frappe/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/show.html", line 31, in top-level template code
    {{ include_script('wiki.bundle.js') }}
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/frappe/frappe-bench/env/lib/python3.6/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'include_script' is undefined
```

**Comment by federicocalvo** [comment]
same issue here!

**Comment by hasnain2808** [comment]
Hi,

Can you please share your frappe, nodejs and python versions?

**Comment by federicocalvo** [comment]
Hi @hasnain2808,

Node v14.17.4
Frappe 13.7.0
ERPNext 13.7.1

**Comment by amutaher** [comment]
Hi @hasnain2808,

Node v14.9.0
Python  3.6.9
Frappe 13.8.0

**Comment by hasnain2808** [comment]
Hey,
Was able to replicate the issue on version 13(13.8.0)
This is happening since the version13(13.8.0, 13.7.0...) branch still uses rollup, and [frappe/wiki](https://github.com/frappe/wiki) is already ported to esbuild constructs(include_script). You should not face these issues on develop. I am having talks with the other members to see if we can find a middle ground.

**Comment by federicocalvo** [comment]
Hi @hasnain2808 , any news of this for Frappe? Thanks!

**Comment by hasnain2808** [comment]
@federicocalvo 
There are two options
1. Maintain a separate version of wiki for version13
2. Add the missing functions in frappe v13, add rollup based build in wiki. If we do this same version of wiki would work with both v13 and develop

**Comment by federicocalvo** [comment]
@hasnain2808 hi! any news of this for the frappe team? thanks!

**Comment by hasnain2808** [comment]
There were a bunch of new changes that were added to the `develop branch`, which are not backported
The Wiki uses some of these new features
So simply adding forward compatibility for `esbuild` in v13 would not be enough.

**Comment by RanaOsamaAsif** [comment]
@hasnain2808 I need to use this can you please let me know what is a workaround? I'm running Frappe in production.

**Comment by chris-kck** [comment]
A workaround I personally did, works but not the most elegant: I created a new bench matching what the wiki app required and served it on a different port. (On the same server)
________________________________

**Comment by hasnain2808** [comment]
Today I installed the Wiki App on a v13 site and started fixing the issues that were coming up due to the incompatibility and then pushed the changes to the version-13 branch. Looks like everything is working apart from the route redirects

There are some routing rules so that the route for edit, new, and revisions do not look bad

https://github.com/frappe/wiki/blob/version-13/wiki/hooks.py#L16

Idk why these are not working on v13 so the routes look a bit bad

http://test:8000/home/edit
vs
http://test:8000/edit?wiki_page=home7

The issue looks like it is in Framework v13, so will need a fix there.

**Comment by MrKovalski** [comment]
What is the actual URL to see the wiki? I tried /home and it shows the default home and the explore products button. I also tried /wiki/test after creating the test page, and it says error processing page with this traceback.


```
Traceback (most recent call last):
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/meofcorse/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/meofcorse/frappe-bench/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/meofcorse/frappe-bench/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 1, in top-level template code
    {% extends "wiki/doctype/wiki_page/templates/wiki_doc.html" %}
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 2, in top-level template code
    {%- from "templates/includes/navbar/navbar_items.html" import render_item -%}
  File "/home/meofcorse/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 77, in block "content"
    {% block page_container %}
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 83, in block "page_container"
    {%- block page_content -%}{%- endblock -%}
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 19, in block "page_content"
    {% include "wiki/doctype/wiki_page/templates/show.html" %}
  File "/home/meofcorse/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/show.html", line 32, in top-level template code
    {{ include_script('wiki.bundle.js') }}
  File "/home/meofcorse/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/meofcorse/frappe-bench/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'include_script' is undefined
```

**Comment by hasnain2808** [comment]
@MrKovalski you're probably installing the master branch on v13
The master branch or the release does not support Frappe v13

**Comment by MrKovalski** [comment]
@hasnain2808 Thanks, its working on version-13 branch.

**Comment by zuron7** [comment]
I think this needs to be changed on the Frappecloud service as well. It's currently pointing to the master branch.

**Comment by federicocalvo** [comment]
thought exactly the same, that it must be unable to be installed also from frappecloud

**Comment by MatthK** [comment]
I installed the wiki on my V.13 installation using the described installation description:

```$ bench get-app https://github.com/frappe/wiki
$ bench --site sitename install-app wiki    # Used the same sitename as the ERPNext installation
```

When I tried to define a first page, I came across this error and found this thread. I guess I have to use the Version 13-branch, but how do I uninstall this one now and then install the other branch? Thanks for your help.
