### ISSUE TITLE
Error installing Wiki

### ISSUE THREAD

**Issue by PatelN123** [frappe/wiki#132]
When installing wiki, this error occurs.

```
 bench get-app https://github.com/frappe/wiki
Getting wiki
$ git clone https://github.com/frappe/wiki  --depth 1 --origin upstream
Cloning into 'wiki'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 146 (delta 22), reused 63 (delta 11), pack-reused 0
Receiving objects: 100% (146/146), 125.05 KiB | 6.25 MiB/s, done.
Resolving deltas: 100% (22/22), done.
Ignoring dependencies of https://github.com/frappe/wiki. To install dependencies                                      use --resolve-deps
Installing wiki
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /                                     home/frappe/frappe-bench/apps/wiki
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@cypress/code-coverage > @cypress/webpack-preprocessor@5.17.0" has unme                                     t peer dependency "@babel/core@^7.0.1".
warning "@cypress/code-coverage > @cypress/webpack-preprocessor@5.17.0" has unme                                     t peer dependency "@babel/preset-env@^7.0.0".
warning "@cypress/code-coverage > @cypress/webpack-preprocessor@5.17.0" has unme                                     t peer dependency "babel-loader@^8.0.2 || ^9".
warning "@cypress/code-coverage > @cypress/webpack-preprocessor@5.17.0" has unme                                     t peer dependency "webpack@^4 || ^5".
warning " > @tiptap/extension-code-block-lowlight@2.0.1" has unmet peer dependen                                     cy "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-code-block-lowlight@2.0.1" has unmet peer dependen                                     cy "@tiptap/extension-code-block@^2.0.0".
warning " > @tiptap/extension-document@2.0.1" has unmet peer dependency "@tiptap                                     /core@^2.0.0".
warning " > @tiptap/extension-image@2.0.1" has unmet peer dependency "@tiptap/co                                     re@^2.0.0".
warning " > @tiptap/extension-link@2.0.1" has unmet peer dependency "@tiptap/cor                                     e@^2.0.0".
warning " > @tiptap/extension-placeholder@2.0.1" has unmet peer dependency "@tip                                     tap/core@^2.0.0".
warning " > @tiptap/extension-table@2.0.1" has unmet peer dependency "@tiptap/co                                     re@^2.0.0".
warning " > @tiptap/extension-table-cell@2.0.1" has unmet peer dependency "@tipt                                     ap/core@^2.0.0".
warning " > @tiptap/extension-table-header@2.0.1" has unmet peer dependency "@ti                                     ptap/core@^2.0.0".
warning " > @tiptap/extension-table-row@2.0.1" has unmet peer dependency "@tipta                                     p/core@^2.0.0".
warning " > @tiptap/extension-text-align@2.0.1" has unmet peer dependency "@tipt                                     ap/core@^2.0.0".
warning " > @tiptap/pm@2.0.1" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/vue-3@2.0.1" has unmet peer dependency "@tiptap/core@^2.0.0"                                     .
warning " > @tiptap/vue-3@2.0.1" has unmet peer dependency "vue@^3.0.0".
warning "@tiptap/vue-3 > @tiptap/extension-bubble-menu@2.0.1" has unmet peer dep                                     endency "@tiptap/core@^2.0.0".
warning "@tiptap/vue-3 > @tiptap/extension-floating-menu@2.0.1" has unmet peer d                                     ependency "@tiptap/core@^2.0.0".
[4/4] Building fresh packages...
Done in 52.36s.
$ bench build --app wiki
✔ Application Assets Linked


yarn run v1.22.19
$ node esbuild --production --apps wiki --run-build-command
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
✘ [ERROR] [plugin vue] Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

147|      <div class="btn btn-primary save-wiki-page-btn btn-sm" @click="saveWikiPage">Save</div>
148|    </div>
149|  </div>
   |
150|  <editor-content :editor="editor" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
151|

    ../wiki/wiki/public/js/tiptap.js:2:19:
      2 │ import Tiptap from "./Tiptap.vue";
        ╵                    ~~~~~~~~~~~~~~

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 ERROR  There were some problems during build

Error: Build failed with 1 error:
../wiki/wiki/public/js/tiptap.js:2:19: ERROR: [plugin: vue] Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

147|      <div class="btn btn-primary save-wiki-page-btn btn-sm" @click="saveWikiPage">Save</div>
148|    </div>
149|  </div>
   |
150|  <editor-content :editor="editor" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
151|
    at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1600:15)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1246:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Terminated
error Command failed with exit code 143.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 86, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps wiki --run-build-command' returned non-zero exit status 143.
ERROR:
subprocess.CalledProcessError: Command 'bench build --app wiki' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 242, in install
    install_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/bench.py", line 351, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError
```

**Comment by TGTGamer** [comment]
Replicated

**Comment by BreadGenie** [comment]
I've commited a fix cbb262e. Please try again now.

**Comment by PatelN123** [comment]
@BreadGenie, new issue on a new installation of Frappe on a new VPS.

```
Installing wiki...
Updating DocTypes for wiki          : [========================================] 100%
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
An error occurred while installing wiki: RetryError[<Future at 0x7f6602d8c2b0 state=finished raised ConnectionError>]
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "env/lib/python3.10/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "apps/frappe/frappe/utils/background_jobs.py", line 363, in get_redis_conn
    redis_connection = RedisQueue.get_connection(**cred)
  File "apps/frappe/frappe/utils/redis_queue.py", line 24, in get_connection
    conn.ping()
  File "env/lib/python3.10/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "env/lib/python3.10/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "env/lib/python3.10/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 304, in install_app
    frappe.get_attr(after_install)()
  File "apps/wiki/wiki/install.py", line 15, in after_install
    page.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1101, in run_post_save_methods
    self.run_method("on_change")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/website/website_generator.py", line 90, in on_change
    self.update_website_search_index()
  File "apps/frappe/frappe/website/website_generator.py", line 177, in update_website_search_index
    frappe.enqueue(update_index_for_path, path=self.route)
  File "apps/frappe/frappe/__init__.py", line 2166, in enqueue
    return frappe.utils.background_jobs.enqueue(*args, **kwargs)
  File "apps/frappe/frappe/utils/background_jobs.py", line 94, in enqueue
    q = get_queue(queue, is_async=is_async)
  File "apps/frappe/frappe/utils/background_jobs.py", line 325, in get_queue
    return Queue(generate_qname(qtype), connection=get_redis_conn(), is_async=is_async)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f6602d8c2b0 state=finished raised ConnectionError>]

frappe@ubuntu-s-1vcpu-1gb-fra1-01:~/frappe-bench$
```

**Comment by BreadGenie** [comment]
Do you have redis installed in your VPS? The pre requisites are: https://frappeframework.com/docs/v14/user/en/installation#pre-requisites .
If you do have it installed maybe it's not running.

**Comment by BreadGenie** [comment]
Closing this since it's resolved.
