### ISSUE TITLE
Editing Page and Adding new Page option is not Working

### ISSUE THREAD

**Issue by rajatnesto** [frappe/wiki#133]
Editing a Wiki Page and adding new Wiki Page is not working with version Update in Frappe Cloud
Commit: 0da2e15de2fbad3eac2ce0b7cb4ccc081323ebd2
Wiki Version: **frappe/wiki:master**
Frappe Version: **v14.31.0**

**Comment by geverit4** [comment]
I'm also seeing this problem.  To reproduce: 
Visit any Wiki page in the new UI
Click on the "Edit" button.
The wiki page panel goes blank.

Note that the following stack trace is returned in the console on loading any Wiki page:

```
runtime-core.esm-bundler.js:244 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.G_ (Tiptap.vue:350:22)
    at Ic (runtime-core.esm-bundler.js:914:44)
    at Ii.A [as fn] (runtime-core.esm-bundler.js:5649:57)
    at Ii.run (reactivity.esm-bundler.js:190:25)
    at S.y.update (runtime-core.esm-bundler.js:5763:56)
    at S (runtime-core.esm-bundler.js:5777:9)
    at Se (runtime-core.esm-bundler.js:5559:9)
    at de (runtime-core.esm-bundler.js:5517:17)
    at m (runtime-core.esm-bundler.js:5119:21)
    at ke (runtime-core.esm-bundler.js:6278:13)
qw @ runtime-core.esm-bundler.js:244
fa @ runtime-core.esm-bundler.js:222
Ic @ runtime-core.esm-bundler.js:943
A @ runtime-core.esm-bundler.js:5649
run @ reactivity.esm-bundler.js:190
S.y.update @ runtime-core.esm-bundler.js:5763
S @ runtime-core.esm-bundler.js:5777
Se @ runtime-core.esm-bundler.js:5559
de @ runtime-core.esm-bundler.js:5517
m @ runtime-core.esm-bundler.js:5119
ke @ runtime-core.esm-bundler.js:6278
mount @ runtime-core.esm-bundler.js:4474
e.mount @ runtime-dom.esm-bundler.js:1607
(anonymous) @ tiptap.js:4
(anonymous) @ tiptap.js:5
runtime-core.esm-bundler.js:244 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.G_ (Tiptap.vue:350:22)
    at Ic (runtime-core.esm-bundler.js:914:44)
    at Ii.A [as fn] (runtime-core.esm-bundler.js:5649:57)
    at Ii.run (reactivity.esm-bundler.js:190:25)
    at S.y.update (runtime-core.esm-bundler.js:5763:56)
    at S (runtime-core.esm-bundler.js:5777:9)
    at Se (runtime-core.esm-bundler.js:5559:9)
    at de (runtime-core.esm-bundler.js:5517:17)
    at m (runtime-core.esm-bundler.js:5119:21)
    at ke (runtime-core.esm-bundler.js:6278:13)
qw @ runtime-core.esm-bundler.js:244
fa @ runtime-core.esm-bundler.js:222
Ic @ runtime-core.esm-bundler.js:943
A @ runtime-core.esm-bundler.js:5649
run @ reactivity.esm-bundler.js:190
S.y.update @ runtime-core.esm-bundler.js:5763
S @ runtime-core.esm-bundler.js:5777
Se @ runtime-core.esm-bundler.js:5559
de @ runtime-core.esm-bundler.js:5517
m @ runtime-core.esm-bundler.js:5119
ke @ runtime-core.esm-bundler.js:6278
mount @ runtime-core.esm-bundler.js:4474
e.mount @ runtime-dom.esm-bundler.js:1607
(anonymous) @ tiptap.js:5
(anonymous) @ tiptap.js:5
```

[epinomy.com-1680887508693.log](https://github.com/frappe/wiki/files/11180324/epinomy.com-1680887508693.log)

**Comment by geverit4** [comment]
It looks like the Master branch for this project is being coded against the "develop" branch of ERPNext.  This can cause any number of problems.  

is it possible to get a "version-14" branch of frappe/wiki that is stable and works on that production version?

**Comment by BreadGenie** [comment]
The issue was caused by Vue version incompatibilty (it was used for the editor). So I've rewritten the editor using vanilla js so it'll work on both develop and v14 from now.

> is it possible to get a "version-14" branch of frappe/wiki that is stable and works on that production version?
I've setup a legacy branch for now.
