### ISSUE TITLE
Installation error on frappe cloud

### ISSUE THREAD

**Issue by cdiethelm** [frappe/wiki#187]
While installing Wiki on frappecloud with a site which had erpnext and frappe installed, I have received an error as follows: 

`Installing wiki...
Updating DocTypes for wiki	    : [======== 			       ] 20%An error occurred while installing wiki: Module import failed for Wiki Space, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/wiki/wiki/wiki/doctype/wiki_space/wiki_space.py", line 11, in <module>
    from wiki.wiki.doctype.wiki_page.search import drop_index, rebuild_index_in_background
  File "apps/wiki/wiki/wiki/doctype/wiki_page/search.py", line 9, in <module>
    from redis.commands.search.field import TextField
ModuleNotFoundError: No module named 'redis.commands'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 407, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 492, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Wiki Space, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'`

**Comment by BreadGenie** [comment]
Can you specify the version of wiki and frappe framework you're trying to install?
If it's for frappe v14 then use `version-14` branch and for frappe `v15/nightly use master` branch

**Comment by cdiethelm** [comment]
@BreadGenie We use the newest version (main). I just tried to install it on an empty site. This works. 

However, on a site that had V14 with wiki installed and wiki lateron removed, it does not work. 

Is there anything that can be done overriding the existing tables?

**Comment by BreadGenie** [comment]
This happened due to the version differnce for redis in `version-14` branch and `develop` branch of frappe. Former needs redisearch installed with redis v3.5.3 as dependency. Meanwhile `develop` branch needs redis v4.5.5.
So if you're installing wiki on version-14 site, use wiki from `version-14` branch with redisearch installed with redis v3.5.3.

**Comment by BreadGenie** [comment]
Just noticed that you mentioned Frappe Cloud
You should only add `version-14` wiki for`version-14` of frappe and `master` wiki for `version-15` and above.

Dependency management will be handled by FC automatically
