### ISSUE TITLE
Error when wrote a new Wiki Page and tried saving it

### ISSUE THREAD

**Issue by umairsy** [frappe/wiki#270]
Extremely sad to see efforts of 30 mins wasted due to error on saving the new Wiki Page!

Edit: As learnt from @shariquerik, the issue was because in Wiki Space DocType, the parent and page's URL were not set. Once this was manually updated, page was restored.

If this issue is already fixed, but FC is missing a deployment, please ensure it is done.

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_renderer.py", line 46, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 521, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 50, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 65, in update_context
    ret = self.doc.get_context(self.context)
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_page.py", line 227, in get_context
    context.wiki_search_scope = self.get_space_route()
  File "apps/wiki/wiki/wiki/doctype/wiki_page/wiki_page.py", line 192, in get_space_route
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 677, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 642, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 593, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Wiki Page doesn't have a Wiki Space associated with it. Please add them via Desk.

**Comment by volkswagner** [comment]
I can confirm the same error:
Installed Apps
Ecommerce Integrations: v1.20.1 (main)
ERPNext: v15.36.3 (version-15)
Frappe Framework: v15.37.0 (version-15)
Frappe HR: v15.25.2 (version-15)
Payments: v0.0.1 (develop)
Wiki: v2.0.0 (master)

If I try to edit a page outside of desk, I don't have the save button and the content
disappears. I get only a window to set a title.


https://github.com/user-attachments/assets/f36c1d8a-0ee2-4cee-b3ca-5d9a330aebc2

**Comment by volkswagner** [comment]
I had bench issues with diverged repo.
`On branch version-15
Your branch and 'upstream/version-15' have diverged,
and have 1 and 236 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)`

I was able to solve my issue with:
`cd apps/hrms
<google-sheets-html-origin><style type="text/css"></style>
git fetch
--
git reset --hard upstream/version-15
git pull
cd ~/frappe-bench
bench update
bench --site mywiki.com migrate
`

**Comment by AyshaHakeem** [comment]
@volkswagner Could you please share a screenshot of the edit view on your Wiki?
Also, just to note, the edit functionalities have been adjusted since the current editor is now in markdown, not rich text.

**Comment by volkswagner** [comment]
Thank you @AyshaHakeem.

I just realized the field type changed to markdown. This is in fact my issue.

Thanks for confirming.
