### ISSUE TITLE
How to access wiki pages ?

### ISSUE THREAD

**Issue by guilmori** [frappe/wiki#47]
I installed the app, I can see the Wiki workspace underneath the Administration menu, and all the masters options.
![image](https://user-images.githubusercontent.com/9451512/142952135-7781d049-e001-4942-8e17-b04a040cc393.png)

Now how to access the Wiki frontend UI ?

I tried going into the website, but cannot see anything related to wiki,

**Comment by federicocalvo** [comment]
@guilmori you have enter to the wiki page lista, and then press in the text of the left "see on the website"

**Comment by guilmori** [comment]
![image](https://user-images.githubusercontent.com/9451512/143326541-3073f209-4066-45e5-a887-2f8d6c786c21.png)

It just brings me to the website, with nothing pertaining to the wiki...
![image](https://user-images.githubusercontent.com/9451512/143326591-e306cfb3-f7d5-4317-b95d-97a03dfde8c1.png)

Fresh new install, along with erpnext.

**Comment by hasnain2808** [comment]
@guilmori 
Your homepage route is same as the wiki page route and the home page  has higher priority so it is getting rendered
Create a new wiki page with some other route and add it to the wiki sidebar. You should be able to open that wiki page.

**Comment by guilmori** [comment]
> @guilmori Your homepage route is same as the wiki page route and the home page has higher priority so it is getting rendered Create a new wiki page with some other route and add it to the wiki sidebar. You should be able to open that wiki page.

Thanks. This name conflict should be mentioned in the installation steps.

I created a new wiki page, click on See on website
![image](https://user-images.githubusercontent.com/9451512/143452013-ce2ef13e-459c-4a95-8bf0-2c46e7798f4b.png)

But I get this error
![image](https://user-images.githubusercontent.com/9451512/143452155-42a7c2f0-a507-4204-8e1d-1bc7cbef300a.png)
Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 1, in top-level template code
    {% extends "wiki/doctype/wiki_page/templates/wiki_doc.html" %}
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 2, in top-level template code
    {%- from "templates/includes/navbar/navbar_items.html" import render_item -%}
  File "/workspace/development/frappe-bench/apps/frappe/frappe/./templates/base.html", line 83, in top-level template code
    {% block content %}
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 77, in block "content"
    {% block page_container %}
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 83, in block "page_container"
    {%- block page_content -%}{%- endblock -%}
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 19, in block "page_content"
    {% include "wiki/doctype/wiki_page/templates/show.html" %}
  File "/workspace/development/frappe-bench/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/show.html", line 32, in top-level template code
    {{ include_script('wiki.bundle.js') }}
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'include_script' is undefined

**Comment by hasnain2808** [comment]
@guilmori the develop branch does not support v13 frappe
You can try version-13
