### ISSUE TITLE
Error when `bench migrate` with PGSQL

### ISSUE THREAD

**Issue by jbtruffault** [frappe/wiki#71]
With commit ac182f434cd20890b02152f25989977d89892793

I think this erros comes from the different syntax between mariadb and postgresql:  https://www.postgresqltutorial.com/postgresql-update-join/

```bash
> bench migrate
....
Executing wiki.wiki.doctype.wiki_page_revision.patches.add_usernames in nextoplait.oplgo.fr (_309770fa87b52987)
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 309, in migrate
    skip_search_index=skip_search_index
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/wiki/wiki/wiki/doctype/wiki_page_revision/patches/add_usernames.py", line 14, in execute
    .set(revision.raised_by_username, user.username)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 52, in execute_query
    return frappe.db.sql(query, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 103, in sql
    return super(PostgresDatabase, self).sql(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 153, in sql
    self._cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "JOIN"
LINE 1: UPDATE "tabWiki Page Revision" JOIN "tabUser" ON "tabUser"."...
                                       ^

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 18, in <module>
    [sys.executable, bench_helper, 'frappe'] + sys.argv[1:],
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/frappe/frappe-bench/env/bin/python', '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py', 'frappe', 'migrate']' returned non-zero exit status 1.
```

**Comment by hasnain2808** [comment]
@jbtruffault 
Verified
Yes this is due to the difference in syntax between MariaDB and postgres
But the patch is using frappe.qb which should run with both mariadb and postgres
So either an issue with the query or with Frappe Query Builder
Also if you skip this patch and update the `raised_by_username` column in Wiki Page Revision with the username of the user set in `raised_by`  you should be good to go

**Comment by jbtruffault** [comment]
Actually, it works nicely with v.1.0.0 ! Sorry for the noise !
