### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by leggettc18** [frappe/wiki#77]
I seem to be getting some errors while trying to install. It looks like something failed on the first install resulting in a partial install and now I can't even attempt to reinstall it.

Versions:
```
erpnext 12.23.0
frappe 12.20.0
wiki 0.0.1
```

Output from `bench get-app https://github.com/frappe/wiki`
```
bench get-app https://github.com/frappe/wiki
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`


Getting wiki
$ git clone https://github.com/frappe/wiki  --depth 1 --origin upstream
Cloning into 'wiki'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 113 (delta 17), reused 36 (delta 2), pack-reused 0
Receiving objects: 100% (113/113), 51.50 KiB | 10.30 MiB/s, done.
Resolving deltas: 100% (17/17), done.

Installing wiki
$ ./env/bin/python -m pip install -q -U -e ./apps/wiki
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/home/frappe/frappe-bench/env/bin/python -m pip install --upgrade pip' command.
$ bench build --app wiki
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

yarn run v1.22.10
$ FRAPPE_ENV=production node rollup/build.js --app wiki
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js

Building wiki assets...

EMPTY_BUNDLE : Generated an empty bundle
Error: File to import not found or unreadable: frappe/public/scss/desk/css_variables.
✔ Built wiki/css/wiki.css
✔ Built wiki/js/wiki.min.js
✨  Done in 0.565s
Done in 2.35s.
$ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
INFO: A newer version of bench is available: 5.5.0 → 5.8.1
```

Output from `bench --site <sitename> install-app wiki`
```
bench --site hr.universitypccare.com install-app wiki
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`


Installing wiki...
Updating DocTypes for wiki          : [==========                              ]An error occurred while installing wiki:
'NoneType' object has no attribute 'options'
```

Output from subsequent attempts to install wiki to the site
```
('Module Def', 'Wiki', IntegrityError(1062, "Duplicate entry 'Wiki' for key 'PRIMARY'"))
```

**Comment by crazy-explore-r** [comment]
Installing wiki...
An error occurred while installing wiki: ('Module Def', 'Wiki', IntegrityError(1062, "Duplicate entry 'Wiki' for key 'PRIMARY'"))
Traceback (most recent call last):
  File "apps/frappe/frappe/model/base_document.py", line 502, in db_insert
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 219, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Wiki' for key 'PRIMARY'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 292, in install_app
    add_module_defs(name, ignore_if_duplicate=force)
  File "apps/frappe/frappe/installer.py", line 623, in add_module_defs
    d.insert(ignore_permissions=True, ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/document.py", line 270, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/base_document.py", line 529, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Wiki', IntegrityError(1062, "Duplicate entry 'Wiki' for key 'PRIMARY'"))

**Comment by kidusch** [comment]
I have the same error:
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Wiki', IntegrityError(1062, "Duplicate entry 'Wiki' for key 'PRIMARY'"))

Any luck on installing wiki?

**Comment by RitvikSardana** [comment]
What is your frappe and erpnext version?

you can use
`bench version`

to check the version

**Comment by azharumar** [comment]
Same error. Using
frappe 14.42.0

**Comment by ravi854** [comment]
Same error. Using
frappe 14.51.0
